/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JGL_JGL_SA */

#ifndef _Included_JGL_JGL_SA
#define _Included_JGL_JGL_SA
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
