/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSDL_JSDL_SDLEvent */

#ifndef _Included_JSDL_JSDL_SDLEvent
#define _Included_JSDL_JSDL_SDLEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
