/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSDL_JSDL_SDL_JoyDeviceEvent */

#ifndef _Included_JSDL_JSDL_SDL_JoyDeviceEvent
#define _Included_JSDL_JSDL_SDL_JoyDeviceEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
