/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSDL_JSDL_SDL_JoyHatEvent */

#ifndef _Included_JSDL_JSDL_SDL_JoyHatEvent
#define _Included_JSDL_JSDL_SDL_JoyHatEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
