/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSDL_JSDL_SDL_CommonEvent */

#ifndef _Included_JSDL_JSDL_SDL_CommonEvent
#define _Included_JSDL_JSDL_SDL_CommonEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
